# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommDisaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=19)),
                ('date', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=4)),
                ('grade', models.CharField(max_length=4)),
                ('picture', models.BinaryField(max_length=8388608)),
                ('note', models.CharField(max_length=200)),
                ('reporting_unit', models.CharField(max_length=50)),
            ],
        ),
    ]
