# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_resolver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commdisaster',
            name='_id',
        ),
        migrations.AlterField(
            model_name='commdisaster',
            name='id',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
    ]
