# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_resolver', '0003_civilstructure_collapserecord_deathstatics_disasterrequest_disatserprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathstatics',
            name='number',
            field=models.IntegerField(),
        ),
    ]
