# Generated by Django 3.0.5 on 2020-06-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_resolver', '0006_brickwoodstructure_crackrecord_debrisrecord_frameworkstructure_gasdisaster_injuredstatics_irrigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterrequest',
            name='id',
            field=models.AutoField(max_length=19, primary_key=True, serialize=False),
        ),
    ]
